### ISSUE TITLE
Beard Too Long

### ISSUE THREAD

**Issue by clayscode** [myersr/starterAlexa#1]
I'm having an issue on line 69 of the RedditReader.py file. I keep trying to compile it but it says "Error: Beard too long". I've read through the PyDocs, located at "https://www.python.org/doc/beardlengths" and it says that beards may not be longer than 42. Please, could you take a look into this?

**Comment by kevinlmadison** [comment]
Yeah I'm having this issue as well on Slackware 13.0.42.22v69. Happens when the lights are on or off. Waiting for a fix. Any updates on beard length?

**Comment by myersr** [comment]
Probably don’t have enough deditated wam. You can get more her [Download Wam](https://www.downloadmoreram.com/download.html)

**Comment by myersr** [comment]
You also might find [this](http://ampersandre.github.io/beard-simulator/) useful if you want to get a glimpse at what you could be.

**Comment by clayscode** [comment]
Can confirm. After I downloaded more deditated wam, the issue cleared up. Strangely, I've also begun growing a beard.
